UNAME    = $(shell uname)
EXE      = analysis
 
VPATH  = .:./interface
vpath %.h ./interface

CSUF   = cc
HSUF   = h
DICTC  = Dict.$(CSUF)
DICTH  = $(patsubst %.$(CSUF),%.h,$(DICTC))

SRCS   = $(wildcard src/*.$(CSUF))
OBJS   = $(patsubst %.$(CSUF), %.o, $(SRCS))

LDFLAGS  = -g
SOFLAGS  = -shared 
CXXFLAGS = -I./interface -I./

CXX       = g++
CXXFLAGS += -Wall -Wno-deprecated

LIBS = 

HDRS = $(wildcard interface/*.$(HSUF))
# Add names of the header files which you do not want to create dictionary of
#HDRS_SKIP  = interface/AnaBase.h
#HDRS_DICT  = $(filter-out $(HDRS_SKIP),$(HDRS)) 
#HDRS_DICT += interface/LinkDef.h
HDRS_DICT = interface/PhysicsObjects.h interface/LinkDef.h

bin: $(EXE) 
all: 
	gmake cint 
	gmake bin 
cint: $(DICTC) 
 
$(DICTC): $(HDRS_DICT)
	@echo "Generating dictionary $(DICTC) and $(DICTH) ..."
	rootcint -f $@ -c $(CXXFLAGS) $^
	perl -pi -e 's#interface/##' $(DICTH)
	@mv $(DICTC) src/ 
	@mv $(DICTH) interface/
 
$(EXE): $(OBJS)
	$(CXX) $(LDFLAGS) $^ -o $@ $(LIBS) `root-config --libs`
 
# Create object files
%.o : %.$(CSUF)
	$(CXX) $(CXXFLAGS) `root-config --cflags` -o $@ -c $<

# makedepend
depend: $(SRCS:.$(CSUF)=.$(CSUF).dep)
	@cat $(notdir $^) > Makefile.dep
	@-rm -f $(notdir $^) $(patsubst %,%.bak,$(notdir $^))
%.dep:
	@touch $(notdir $@)
	rmkdepend -f$(notdir $@) -- $(CXXFLAGS) `root-config --cflags` -- $*
include Makefile.dep

# Clean 
.PHONY   : clean 
clean : 
	@-rm $(OBJS) $(EXE) interface/$(DICTH) src/$(DICTC)
