START
dataType data
readTrk  0
readTrigObject 0
puHistFile /cmshome/sarkar/CMSSW_4_2_8_patch7/src/VHTauTau/TreeAnalyzer/05Mar2012/reweightFunctionFall11.root
histFile  SingleMu_1.root
logFile   SingleMu_1.out
eventFile SingleMu_events_1.out
logOption 0
maxEvent -1
vtxCutList ndf=7 dxy=2 z=24
muonCutList eta=2.1 relIso=0.3 trkHits=10 pixHits=1 globalChi2=10.0 trkD0=0.045 dB=0.02 vtxDistZ=0.2 nChambers=1 nMatches=1 nMatchedStations=2
electronCutList pt=10.0 eta=2.5 eleId=6.5 dB=0.02 scEtaLow=1.4442 scEtaUp=1.566 missingHits=1
tauCutList eta=2.3 dz=0.2
bjetCutList eta=2.5 pt=20 trackCount=3.3
evselCutList ptMuon=30 ptTau1=22 ptTau2=15 drMuTau1=0.3 drMuTau2=0.3 drTau1Tau2=0.3
studyTrigger 1
trigPathList HLT_IsoMu30 HLT_Mu30 HLT_IsoMu30_eta2p1
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_100_3_0a2.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_101_2_zA4.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_102_2_8vh.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_103_2_wqk.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_104_2_NJo.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_105_2_dTn.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_106_2_rdA.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_107_2_akh.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_108_2_yNk.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_109_2_fVM.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_10_1_lru.root
inputFile /lustre/cms/store/user/sarkar/05Mar2012/SingleMu_V4/SingleMu_V4_110_2_FO0.root
END
